# Generated by Django 3.0.6 on 2020-06-12 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_remove_posts_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumuser',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
