# Generated by Django 3.0.6 on 2020-06-14 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_forumuser_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forumuser',
            name='picture',
            field=models.ImageField(blank=True, default='discord.png', null=True, upload_to=''),
        ),
    ]
